version: '3.8'
services:
  quicksilver:
    image: quicksilverzone/quicksilver:latest
    hostname: quicksilver
    volumes:
      - ./data/qstest-1:/quicksilver/.quicksilverd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 26657:26657
      - 1317:1317
  quicksilver2:
    image: quicksilverzone/quicksilver:latest
    hostname: quicksilver2
    volumes:
      - ./data/qstest-1a:/quicksilver/.quicksilverd
    build:
      context: .
      dockerfile: Dockerfile
  quicksilver3:
    image: quicksilverzone/quicksilver:latest
    hostname: quicksilver3
    volumes:
      - ./data/qstest-1b:/quicksilver/.quicksilverd
    build:
      context: .
      dockerfile: Dockerfile
  testzone1-1:
    image: gaia:v9.0.1-debug
    hostname: testzone1-1
    volumes:
      - ./data/lstest-1:/gaia/.gaia
    command:
      - gaiad
      - start
    ports:
    - 27657:26657
    - 23137:1317
  testzone1-2:
    image: gaia:v9.0.1
    hostname: testzone1-2
    volumes:
      - ./data/lstest-1a:/gaia/.gaia
    command:
      - gaiad
      - start
  testzone1-3:
    image: gaia:v9.0.1
    hostname: testzone1-3
    volumes:
      - ./data/lstest-1b:/gaia/.gaia
    command:
      - gaiad
      - start
  testzone1-4:
    image: gaia:v9.0.1
    hostname: testzone1-4
    volumes:
      - ./data/lstest-1c:/gaia/.gaia
    command:
      - gaiad
      - start
  testzone2-1:
    image: quicksilverzone/qsosmosis:v12.1.0
    hostname: testzone2-1
    build:
      context: .
      dockerfile: Dockerfile.osmosis
    volumes:
      - ./data/lstest-2:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  testzone2-2:
    image: quicksilverzone/qsosmosis:v12.1.0
    hostname: testzone2-2
    volumes:
      - ./data/lstest-2a:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  testzone2-3:
    image: quicksilverzone/qsosmosis:v12.1.0
    hostname: testzone2-3
    volumes:
      - ./data/lstest-2b:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  testzone2-4:
    image: quicksilverzone/qsosmosis:v12.1.0
    hostname: testzone2-4
    volumes:
      - ./data/lstest-2c:/osmosis/.osmosisd
    command:
      - osmosisd
      - start
  hermes:
    image: quicksilverzone/hermes:v1.0.0
    hostname: hermes
    volumes:
      - ./data/hermes:/hermes/.hermes
    command:
      - hermes
      - start
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.hermes
  icq:
    image: quicksilverzone/interchain-queries:latest
    volumes:
      - ./data/icq:/icq/.icq
    command:
      - interchain-queries
      - run
    restart: always
  icq2:
    image: quicksilverzone/interchain-queries:v0.6.2
    volumes:
      - ./data/icq2:/icq/.icq
    command:
      - interchain-queries
      - run
    restart: always
  relayer:
    image: quicksilverzone/relayer:v2.1.1
    build:
      context: .
      dockerfile: Dockerfile.relayer
    volumes:
      - ./data/rly:/rly/.relayer
    command:
      - rly
      - start
      - demo
      #- -p
      #- events
      #- -b
      #- "100"
    restart: always
